name: Dockerize Next.js web application
on: push

permissions:
  contents: read

jobs:
  build-container:
    name: Build Docker Container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: action/checkout@v4
      - name: Publish to Github Packages
        uses: docker/build-push-action@v5
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}/next
          tags: latest, ${{ github.run_number }}

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexss2000/next
          tags: latest, ${{ github.run_number }}
